import { useState, useEffect, useCallback, useRef } from "react";
import { Sparkles, RefreshCw, Loader2, RotateCcw } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { generateClientSummary, rerunClientPipeline } from "@/services/agentService";
import { toast } from "sonner";
import type { AppClient } from "@/types";
import ReportRenderer from "./ReportRenderer";

interface Props {
  client: AppClient;
  onSummaryGenerated?: (summary: string) => void;
}

const STAGES = ["Researching", "Drafting", "Pending_Approval", "Scheduled"] as const;
const STAGE_LABELS: Record<(typeof STAGES)[number], string> = {
  Researching: "Researcher",
  Drafting: "Strategist",
  Pending_Approval: "Creative",
  Scheduled: "Butler",
};

const WORKFORCE_MESSAGES: Record<(typeof STAGES)[number], string> = {
  Researching: "Researcher is analyzing the brand and website.",
  Drafting: "Strategist is building the content plan.",
  Pending_Approval: "Creative has drafts ready for review.",
  Scheduled: "Butler has the workflow prepared for scheduling.",
};

function getStageIndex(status: string | null): number {
  const index = STAGES.indexOf((status as (typeof STAGES)[number]) ?? "Researching");
  return index === -1 ? 0 : index;
}

export default function BrandProfileCard({ client, onSummaryGenerated }: Props) {
  const [liveClient, setLiveClient] = useState<AppClient>(client);
  const [summary, setSummary] = useState<string>(client.ai_summary || "");
  const [loading, setLoading] = useState(false);
  const autoGeneratedForClient = useRef<string | null>(null);

  const generate = useCallback(async () => {
    setLoading(true);
    try {
      const text = await generateClientSummary(liveClient);
      setSummary(text);
      onSummaryGenerated?.(text);
      const { error } = await supabase.from("clients").update({ ai_summary: text }).eq("id", liveClient.id);
      if (error) throw error;
    } catch {
      toast.error("Couldn't generate brand summary.");
    } finally {
      setLoading(false);
    }
  }, [liveClient, onSummaryGenerated]);

  useEffect(() => {
    setLiveClient(client);
    setSummary(client.ai_summary || "");
  }, [client]);

  useEffect(() => {
    const channel = supabase
      .channel(`brand-profile-${client.id}`)
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "clients", filter: `id=eq.${client.id}` },
        (payload) => {
          const nextClient = payload.new as Partial<AppClient>;
          setLiveClient((current) => ({ ...current, ...nextClient }));
          if (typeof nextClient.ai_summary === "string") {
            setSummary(nextClient.ai_summary);
            onSummaryGenerated?.(nextClient.ai_summary);
          }
        },
      )
      .subscribe();

    return () => {
      void supabase.removeChannel(channel);
    };
  }, [client.id, onSummaryGenerated]);

  useEffect(() => {
    if (!liveClient.ai_summary) {
      if (autoGeneratedForClient.current === liveClient.id) return;
      autoGeneratedForClient.current = liveClient.id;
      generate();
      return;
    }
    autoGeneratedForClient.current = liveClient.id;
    setSummary(liveClient.ai_summary);
  }, [liveClient.ai_summary, liveClient.id, generate]);

  const platforms: string[] = liveClient.platforms || [];
  const currentStage = (liveClient.pipeline_status as (typeof STAGES)[number]) ?? "Researching";
  const stageIndex = getStageIndex(liveClient.pipeline_status);
  const showResearch = Boolean(liveClient.research_notes);
  const showStrategy = Boolean(liveClient.content_strategy);

  return (
    <div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3">
      {/* Header row */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center shrink-0">
            <Sparkles className="w-4 h-4 text-primary" />
          </div>
          <div>
            <p className="font-display font-semibold text-sm text-foreground">{liveClient.company_name}</p>
            <p className="text-xs text-muted-foreground font-body">
              {liveClient.industry}
              {platforms.length > 0 && (
                <> · {platforms.join(", ")}</>
              )}
              {liveClient.brand_voice && (
                <> · <span className="text-primary/80">{liveClient.brand_voice} voice</span></>
              )}
            </p>
          </div>
        </div>
        <button
          onClick={generate}
          disabled={loading}
          title="Refresh analysis"
          className="text-muted-foreground hover:text-foreground transition-colors shrink-0 mt-0.5"
        >
          {loading
            ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
            : <RefreshCw className="w-3.5 h-3.5" />
          }
        </button>
      </div>

      {/* AI Summary */}
      <div className="text-sm font-body text-muted-foreground leading-relaxed">
        {loading && !summary ? (
          <div className="flex items-center gap-2 text-primary/70">
            <Loader2 className="w-3.5 h-3.5 animate-spin" />
            <span>Analyzing your brand…</span>
          </div>
        ) : (
          <p>{summary || "No summary yet — click refresh to generate."}</p>
        )}
      </div>

      <div className="rounded-lg border border-border/60 bg-background/60 p-3 space-y-2">
        <div className="flex items-center justify-between gap-3">
          <div>
            <p className="text-xs font-display font-semibold uppercase tracking-wider text-muted-foreground">
              Workforce Status
            </p>
            <p className="text-xs text-muted-foreground font-body">
              {WORKFORCE_MESSAGES[currentStage]}
            </p>
          </div>
          <span className="text-[11px] px-2 py-1 rounded-full border border-primary/30 bg-primary/10 text-primary font-display font-semibold">
            {STAGE_LABELS[currentStage]}
          </span>
        </div>

        <div className="grid grid-cols-4 gap-1.5">
          {STAGES.map((stage, index) => (
            <div
              key={stage}
              className={`rounded-md px-2 py-1 text-center text-[11px] font-body border ${
                index < stageIndex
                  ? "bg-primary text-primary-foreground border-primary"
                  : index === stageIndex
                  ? "bg-primary/10 text-primary border-primary/40"
                  : "bg-secondary/70 text-muted-foreground border-border"
              }`}
            >
              {STAGE_LABELS[stage]}
            </div>
          ))}
        </div>

        <details className="group rounded-md border border-border/60 bg-background/70 px-3 py-2">
          <summary className="cursor-pointer list-none flex items-center justify-between gap-3">
            <p className="text-sm font-display font-semibold text-foreground">Research</p>
            <span className="text-xs text-muted-foreground">{showResearch ? "View" : "Waiting"}</span>
          </summary>
          <div className="mt-3">
            {liveClient.research_notes
              ? <ReportRenderer content={liveClient.research_notes} type="research" />
              : <p className="text-sm text-muted-foreground">The Researcher has not produced notes yet.</p>}
          </div>
        </details>

        <details className="group rounded-md border border-border/60 bg-background/70 px-3 py-2">
          <summary className="cursor-pointer list-none flex items-center justify-between gap-3">
            <p className="text-sm font-display font-semibold text-foreground">Strategy</p>
            <span className="text-xs text-muted-foreground">{showStrategy ? "View" : "Waiting"}</span>
          </summary>
          <div className="mt-3">
            {liveClient.content_strategy
              ? <ReportRenderer content={liveClient.content_strategy} type="strategy" />
              : <p className="text-sm text-muted-foreground">The Strategist has not generated a content plan yet.</p>}
          </div>
        </details>

        {/* Brand Identity — extracted from website by Agent 1 */}
        {(() => {
          const c = liveClient as Record<string, unknown>;
          const hasColors = c.brand_primary_color || c.brand_secondary_color || c.brand_accent_color;
          const hasStyle = c.brand_visual_style;
          const tags = c.brand_personality_tags as string[] | null;
          const notes = c.brand_notes as string | null;
          if (!hasColors && !hasStyle && !tags?.length && !notes) return null;
          return (
            <details className="group rounded-md border border-border/60 bg-background/70 px-3 py-2">
              <summary className="cursor-pointer list-none flex items-center justify-between gap-3">
                <p className="text-sm font-display font-semibold text-foreground">Brand Identity</p>
                <span className="text-xs text-muted-foreground">View</span>
              </summary>
              <div className="mt-3 space-y-3">
                {hasColors && (
                  <div className="space-y-1.5">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Colors</p>
                    <div className="flex gap-3">
                      {([
                        { key: 'brand_primary_color', label: 'Primary' },
                        { key: 'brand_secondary_color', label: 'Secondary' },
                        { key: 'brand_accent_color', label: 'Accent' },
                      ] as const).map(({ key, label }) =>
                        c[key] ? (
                          <div key={key} className="flex items-center gap-1.5">
                            <span
                              className="w-5 h-5 rounded-full border border-border/60 shrink-0"
                              style={{ backgroundColor: c[key] as string }}
                            />
                            <span className="text-xs text-muted-foreground">{label}</span>
                            <span className="text-xs font-mono text-foreground/60">{c[key] as string}</span>
                          </div>
                        ) : null
                      )}
                    </div>
                  </div>
                )}
                {hasStyle && (
                  <div className="space-y-1">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Visual Style</p>
                    <span className="inline-block px-2.5 py-1 rounded-md bg-primary/10 border border-primary/20 text-xs text-foreground">
                      {c.brand_visual_style as string}
                    </span>
                  </div>
                )}
                {tags && tags.length > 0 && (
                  <div className="space-y-1.5">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Personality</p>
                    <div className="flex flex-wrap gap-1.5">
                      {tags.map((tag) => (
                        <span key={tag} className="px-2 py-0.5 rounded-full bg-secondary border border-border/40 text-xs text-muted-foreground">
                          {tag}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {notes && (
                  <div className="space-y-1">
                    <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">Notes</p>
                    <p className="text-xs text-muted-foreground leading-relaxed">{notes}</p>
                  </div>
                )}
              </div>
            </details>
          );
        })()}
      </div>
    </div>
  );
}
